name: Deploy to Lambda with Zappa

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: run venv
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: deploy with zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EVERY_CAL_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EVERY_CAL_SECRET_KEY_ID }}
        run: |
          zappa update dev
